### ISSUE TITLE
No DTC listed

### ISSUE THREAD

**Issue by tones111** [Comer352L/FreeSSM#2]
2005 USDM STi which is throwing a CEL and going into limp-home mode.  When I try to read the DTC codes none are listed.  The cruise control page does show a shop code.  The dealer was able to pull a code of P0340 and the description matched what's listed in SSMprotocol2_def_en.cpp.  I'm unsure why FreeSSM is unable to list it.

**Comment by tones111** [comment]
Looks like I'm throwing CEL again and seeing similar behavior as before.  No DTCs listed in FreeSSM, but I do get a P0304 (cylinder 4 misfire) from EcuExplorer.

When looking at the output from EcuExplorer the only addresses reading non-zero are
00 00 C1 = 08
00 00 C2 = 01

From the output...
19:29:48.421 - <--  80 10 F0 20 A8 00 00 00  B8 00 00 B9 00 00 BA 00 - .........
.......
19:29:48.421 - <--  00 BB 00 00 BC 00 00 BD  00 00 BE 00 00 BF 00 00 - .........
.......
19:29:48.421 - <--  C0 00 00 C1 A5                                    - .....
19:29:48.452 - <--  80 F0 10 0B E8 00 00 00  00 00 00 00 00 00 08 7B  - ........


19:29:48.561 - <--  80 10 F0 20 A8 00 00 00  C2 00 00 C3 00 00 C4 00 - .........
.......
19:29:48.561 - <--  00 C5 00 00 C6 00 00 C7  00 00 C8 00 00 C9 00 00 - .........
.......
19:29:48.561 - <--  CA 00 00 CB 09                                    - .....
19:29:48.592 - <--  80 F0 10 0B E8 01 00 00  00 00 00 00 00 00 00 74  - ........

If I look at a log from FreeSSM I don't see it attempting to read those memory addresses, but I also don't know what those addresses decode to.

I would love to try and help debug this while it's still throwing the code, but unsure how to help.  My ECU init string is...
   80 F0 10 39 FF A2 10 11 3D 12 59 40 06 73 FA CB
   A6 2B 81 FE A8 00 00 00 60 CE 54 F8 B1 E4 80 00
   00 00 00 00 00 00 DC 00 00 75 1E 30 C0 F0 22 00
   00 43 FB 00 F1 00 00 00 00 00 00 00 F0 B8

But I doubt that helps much since we're looking for DTC codes which aren't related to ECU flags.  Any ideas on how I can help troubleshoot?

**Comment by tones111** [comment]
I've found the problem.

In SSM2definitionsInterface::diagnosticCodes(...) there's an obdDTCs boolean that's initialized to false and never set thereafter.  This prevents addresses 0x99 through 0xAD from being read.  Initializing the variable to true allows the DTCs to show up as I would expect.

**Comment by Comer352L** [comment]
Good catch !
I will apply this with a different description (keeping you as author).
Thanks !
