### ISSUE TITLE
Actuator Test - EGR

### ISSUE THREAD

**Issue by ajl236** [Comer352L/FreeSSM#21]
Great project.  I tried to run the EGR actuator test but the code (ActuatorTestDlg.cpp:44) won't run if the engine is running.  The Subaru manual for 03-09 Legacy Outback (http://jdmfsm.info/Auto/Japan/Subaru/Legacy_Outback/2007/Legacy%202007/contents/data/S088/S088615a16.html) describes the System Operation Check for the EGR valve requires the engine to be started.   If anyone got the EGR valve control test running please let me know or if I'm posting this on the wrong board.

**Comment by Comer352L** [comment]
Two types of EGR valve test exist.

The first one is a simple actuator on/off test, which is supported by most engines.
The original SSM offers this test under "System Operation Check Modes" / "Actutor ON/OFF Operation" / "EGR Solenoid Valve".
This test is supported by FreeSSM and and requires the engine to be NOT running (original SSM checks this condition, too).

The second test is an enhanced test, which allows to control the number of EGR steps.
It has been introduced ~2007 and is not supported by older models.
The original SSM offers this test separately as "System Operation Check Modes" / "EGR Valve Control".
It is not (yet ?) supported by FreeSSM an indeed requires the engine to be running.

**Comment by ajl236** [comment]
Thanks @Comer352L , this explains what I am seeing.
