### ISSUE TITLE
Compile error on Windows

### ISSUE THREAD

**Issue by ajl236** [Comer352L/FreeSSM#22]
I would really like to compile this project on Windows and followed the readme file as I've not used g++ before. 

Downloaded the project source and installed MinGW-gcc440_1.zip  to c:\mingw\ and then installed QT 4.8.5 mingw edition and added both \bin folders to the environment PATH.  

`g++ --version // reports 4.4.0`
`qmake`
`make debug // reports -std=c++11 is not supported`

so modified FreeSSM.pro:147 because maybe 4.4.0 doesn't support full c++11 to; 
`QMAKE_CXXFLAGS += -std=c++0x`

but after rerunning qmake and make debug get;

`c:\mingw\bin\../lib/gcc/mingw32/4.4.0/include/c++/cwchar:160: error: '::swprintf' has not been declared`
`c:\mingw\bin\../lib/gcc/mingw32/4.4.0/include/c++/cwchar:169: error: '::vswprintf' has not been declared`
`..\..\Qt\4.8.5\include/QtCore/../../src/corelib/concurrent/qtconcurrentrun.h:113: confused by earlier errors, bailing out`

After searching I then tried adding -U__STRICT_ANSI__ to FreeSSM.pro and editing cwchars to comment out swprintf and vswprintf but with no luck.   

Thanks for any help

**Comment by Comer352L** [comment]
Wow, g++ 4.4.0 is ... ~10 years old ?!

The MinGW version of g++ always lags behind the Unix version, Qt never ships the latest MinGW version, Qt 4.8.5 has been released a long time ago, ...

So if you are forced to use Windows, better use Qt5 instead (it comes with a newer version MinGW/g++).
