### ISSUE TITLE
Error Compiling on Windows 10

### ISSUE THREAD

**Issue by themodfatherinc** [Comer352L/FreeSSM#24]
getting this when i run make release. any ideas how to get this working? i spent hours finding mingw etc and got this far finally only to be stopped here. compile on linux went fine but i cant seem to get the windows one going. unless i can somehow compile a windows exe on linux?

C:\FreeSSM>make release
mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory `C:/FreeSSM'
c:\Qt\4.8.5\bin\uic.exe ui\FreeSSM.ui -o ui_FreeSSM.h
c:\Qt\4.8.5\bin\uic.exe ui\Preferences.ui -o ui_Preferences.h
c:\Qt\4.8.5\bin\uic.exe ui\About.ui -o ui_About.h
c:\Qt\4.8.5\bin\uic.exe ui\ControlUnitDialog.ui -o ui_ControlUnitDialog.h
c:\Qt\4.8.5\bin\uic.exe ui\CUinfo_Engine.ui -o ui_CUinfo_Engine.h
c:\Qt\4.8.5\bin\uic.exe ui\CUinfo_Transmission.ui -o ui_CUinfo_Transmission.h
c:\Qt\4.8.5\bin\uic.exe ui\CUinfo_simple.ui -o ui_CUinfo_simple.h
c:\Qt\4.8.5\bin\uic.exe ui\CUcontent_DCs_engine.ui -o ui_CUcontent_DCs_engine.h
c:\Qt\4.8.5\bin\uic.exe ui\CUcontent_DCs_twoMemories.ui -o ui_CUcontent_DCs_twoMemories.h
c:\Qt\4.8.5\bin\uic.exe ui\CUcontent_DCs_stopCodes.ui -o ui_CUcontent_DCs_stopCodes.h
c:\Qt\4.8.5\bin\uic.exe ui\CUcontent_MBsSWs.ui -o ui_CUcontent_MBsSWs.h
c:\Qt\4.8.5\bin\uic.exe ui\CUcontent_MBsSWs_tableView.ui -o ui_CUcontent_MBsSWs_tableView.h
c:\Qt\4.8.5\bin\uic.exe ui\CUcontent_Adjustments.ui -o ui_CUcontent_Adjustments.h
c:\Qt\4.8.5\bin\uic.exe ui\CUcontent_sysTests.ui -o ui_CUcontent_sysTests.h
c:\Qt\4.8.5\bin\uic.exe ui\AddMBsSWsDlg.ui -o ui_AddMBsSWsDlg.h
c:\Qt\4.8.5\bin\uic.exe ui\ActuatorTestDlg.ui -o ui_ActuatorTestDlg.h
g++ -c -pipe -fno-gcse -std=c++11 -O2 -frtti -fexceptions -mthreads -Wall -Wextra -DUNICODE -DTIXML_USE_STL -DQT_DLL -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_THREAD_SUPPORT -DQT_NEEDS_QMAIN -I"..\Qt\4.8.5\include\QtCore" -I"..\Qt\4.8.5\include\QtGui" -I"..\Qt\4.8.5\include" -I"." -I"src" -I"src\tinyxml" -I"src\windows" -I"..\Qt\4.8.5\include\ActiveQt" -I"release" -I"." -I"..\Qt\4.8.5\mkspecs\default" -o release\main.o src\main.cpp
g++: CreateProcess: No such file or directory
cc1plus.exe: error: unrecognized command line option "-std=c++11"
mingw32-make[1]: *** [release/main.o] Error 1
mingw32-make[1]: Leaving directory `C:/FreeSSM'
mingw32-make: *** [release] Error 2

**Comment by Comer352L** [comment]
See [issue #22](https://github.com/Comer352L/FreeSSM/issues/22).
In short: on Windows you have to use Qt5.
I really need to update the documentation...
You shouldn't have to install MinGW manually, the Qt5 installer should do this for you (or at least assist you).

**Comment by ajl236** [comment]
Win10;

Install QT 5.8.0 open source with both MingGW options selected
Ensure environment variable PATH includes;
C:\Qt\Qt5.8.0\Tools\mingw530_32\bin
C:\Qt\Qt5.8.0\5.8\mingw53_32\bin
Enter source directory
qmake
mingw32-make debug
mingw32-make translation
mingw32-make debug-install // files created in c:\freessm
