### ISSUE TITLE
OP 2.0/J2534-Windows XP

### ISSUE THREAD

**Issue by paladinshiva** [Comer352L/FreeSSM#32]
To continue the quest of making Tactrix work.
After compiling with latest code:
When compiling as release - Same error upon accessing J2534, except it takes about a minute until it will state the error now.
When using freessm > logfile.log on a release, returns empty log file each time.
When compiling debug, returns an error. Copy of the command prompt verbose attached.
[debugcompileerror.txt](https://github.com/Comer352L/FreeSSM/files/3244216/debugcompileerror.txt)

**Comment by Comer352L** [comment]
> When using freessm > logfile.log on a release, returns empty log file each time.

Looks like the output does not get written to the file before you leave the program.
At least on Win 7, but I doubt there is any difference to Win XP.
> When compiling debug, returns an error. Copy of the command prompt verbose attached.

You've got me. I didn't test the last commit properly. :/
Fixed.

**Comment by paladinshiva** [comment]
> > When using freessm > logfile.log on a release, returns empty log file each time.
> 
> Looks like the output does not get written to the file before you leave the program.
> At least on Win 7, but I doubt there is any difference to Win XP.
> 
Nope. Will not write anything in the log in release compilation.
> > When compiling debug, returns an error. Copy of the command prompt verbose attached.
> 
> You've got me. I didn't test the last commit properly. :/
> Fixed.
Indeed :)


Attached logfile using debug compilation.
This time when testing interface, gave a second error(only when using DEBUG compile), of something about SSM2.
[logfile.log](https://github.com/Comer352L/FreeSSM/files/3245647/logfile.log)

**Comment by Comer352L** [comment]
> > > When using freessm > logfile.log on a release, returns empty log file each time.
> > 
> > 
> > Looks like the output does not get written to the file before you leave the program.
> > At least on Win 7, but I doubt there is any difference to Win XP.
> 
> Nope. Will not write anything in the log in release compilation.

You will never get an debugging output without compiling as "debug". ;-)

> Attached logfile using debug compilation.
> This time when testing interface, gave a second error(only when using DEBUG compile), of something about SSM2.
> [logfile.log](https://github.com/Comer352L/FreeSSM/files/3245647/logfile.log)

Urgh... this one is even worse than the previous one.
At first glance, I can see 4(!) issues...
But let me check that carefully. I will also have to read the spec again.

**Comment by paladinshiva** [comment]
> You will never get any debugging output without compiling as "debug". ;-)
Oops... Somehow I've thought that was the feature for release. Brain glitch😳

Yes, there are errors from testing the interface and also for accessing the engine.
Repeated twice to make sure...

**Comment by Comer352L** [comment]
Can you please test branch "op20-test" ?
Please send me the debugging output even if everything works fine.

**Comment by paladinshiva** [comment]
> Can you please test branch "op20-test" ?
> Please send me the debugging output even if everything works fine.

Currently on a road trip in Northern Territories...
I'll come back and do it right away.

**Comment by paladinshiva** [comment]
I've tested both release and debug.
Now it gives all the same errors, but when I turn Engine On, the engine screen will reappear.
Clicking any button from there however will result in an error and an exit from the screen.
Log is attached.
[log.txt](https://github.com/Comer352L/FreeSSM/files/3304194/log.txt)

**Comment by paladinshiva** [comment]
Posted and then realized I used wrong build. Will update.

**Comment by paladinshiva** [comment]
Just used the debug build. OP20 test branch.
Interface testing will fail, also now the engine tab does not recognize ECU at all.
Tried with engine off, ignition on and engine on, ignition on.
Log file attached.
Please let me know what else I can do.
[log.txt](https://github.com/Comer352L/FreeSSM/files/3304287/log.txt)

**Comment by Comer352L** [comment]
Next round. ;)

**Comment by Comer352L** [comment]
If things are working now, then please change line 261 in J2534DiagInterface to
`CfgItems[0].Value = 0;	// [04.04-API: *0.5ms]`
and create another log.
I would like to see how the interface deals with this value...

**Comment by paladinshiva** [comment]
Awesome! Round 2... Fight!
I just got called in and will get back Thu or Friday. I'll do it right away then...

**Comment by paladinshiva** [comment]
Wow!!!
Everything works and even when changing that parameter!!!
You're a monster!!!
[log.txt](https://github.com/Comer352L/FreeSSM/files/3317217/log.txt)
[logfile.log](https://github.com/Comer352L/FreeSSM/files/3317218/logfile.log)

**Comment by Comer352L** [comment]
That's great, but unfortunately you've sent old logs. ;)
The logs from the previous 2 tests should contain multiple lines with "PASSTHRU_MSG #1".

**Comment by paladinshiva** [comment]
Oh no... Are you sure? This was the output I got...

**Comment by paladinshiva** [comment]
You were absolutely right.
USB flash ejecting bug.
[log261.txt](https://github.com/Comer352L/FreeSSM/files/3318791/log261.txt)
[log.txt](https://github.com/Comer352L/FreeSSM/files/3318792/log.txt)

**Comment by Comer352L** [comment]
Perfect, thanks. All issues are gone. :)

That has been a very interesting debugging session and a journey through the specs.
This interface does some things different than the interfaces I've seen so far.
But I can't blame it for doing anything wrong, it complies with the spec.
In fact it unveils some parts of the spec which leave (too) much room for interpretation or are unfortunate design.

**Comment by Comer352L** [comment]
I have pulled the fixes into the "master" branch, many thanks for testing !
