### ISSUE TITLE
Does not Compile on 18.04 LTS

### ISSUE THREAD

**Issue by W1JPI** [Comer352L/FreeSSM#33]
Hi, 

Thank you for this great project. I tried to compile the latest version of FreeSSM, but I have been unable to build it on Ubuntu 18.04 LTS since the recent updates. I believe the problem may lie with FreeSSM.pro, I am still troubleshooting, so I will post an update if I am able to resolve the issue myself. Please see the below output of "sudo make release-install" on a stock system with qt5-default installed. 

`dev@dev:~/FreeSSM$ sudo make release-install
make -f Makefile.Release install
make[1]: Entering directory '/home/dev/FreeSSM'
/usr/lib/qt5/bin/qmake -install qinstall -exe FreeSSM /home/dev/FreeSSM/FreeSSM
Error copying FreeSSM to /home/dev/FreeSSM/FreeSSM: Cannot open FreeSSM for input
Makefile.Release:1961: recipe for target 'install_target' failed
make[1]: [install_target] Error 3 (ignored)
strip /home/dev/FreeSSM/FreeSSM
strip: '/home/dev/FreeSSM/FreeSSM': No such file
Makefile.Release:1961: recipe for target 'install_target' failed
make[1]: [install_target] Error 1 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/doc/bg.jpg /home/dev/FreeSSM/doc/bg.jpg
Error copying /home/dev/FreeSSM/doc/bg.jpg to /home/dev/FreeSSM/doc/bg.jpg: Cannot open /home/dev/FreeSSM/doc/bg.jpg for input
Makefile.Release:1971: recipe for target 'install_doctarget' failed
make[1]: [install_doctarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/doc/help_de.html /home/dev/FreeSSM/doc/help_de.html
Error copying /home/dev/FreeSSM/doc/help_de.html to /home/dev/FreeSSM/doc/help_de.html: Cannot open /home/dev/FreeSSM/doc/help_de.html for input
Makefile.Release:1971: recipe for target 'install_doctarget' failed
make[1]: [install_doctarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/doc/help_en.html /home/dev/FreeSSM/doc/help_en.html
Error copying /home/dev/FreeSSM/doc/help_en.html to /home/dev/FreeSSM/doc/help_en.html: Cannot open /home/dev/FreeSSM/doc/help_en.html for input
Makefile.Release:1971: recipe for target 'install_doctarget' failed
make[1]: [install_doctarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/definitions/SSM1defs_ABS.xml /home/dev/FreeSSM/definitions/SSM1defs_ABS.xml
Error copying /home/dev/FreeSSM/definitions/SSM1defs_ABS.xml to /home/dev/FreeSSM/definitions/SSM1defs_ABS.xml: Cannot open /home/dev/FreeSSM/definitions/SSM1defs_ABS.xml for input
Makefile.Release:1984: recipe for target 'install_defstarget' failed
make[1]: [install_defstarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/definitions/SSM1defs_AirConditioning.xml /home/dev/FreeSSM/definitions/SSM1defs_AirConditioning.xml
Error copying /home/dev/FreeSSM/definitions/SSM1defs_AirConditioning.xml to /home/dev/FreeSSM/definitions/SSM1defs_AirConditioning.xml: Cannot open /home/dev/FreeSSM/definitions/SSM1defs_AirConditioning.xml for input
Makefile.Release:1984: recipe for target 'install_defstarget' failed
make[1]: [install_defstarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/definitions/SSM1defs_CruiseControl.xml /home/dev/FreeSSM/definitions/SSM1defs_CruiseControl.xml
Error copying /home/dev/FreeSSM/definitions/SSM1defs_CruiseControl.xml to /home/dev/FreeSSM/definitions/SSM1defs_CruiseControl.xml: Cannot open /home/dev/FreeSSM/definitions/SSM1defs_CruiseControl.xml for input
Makefile.Release:1984: recipe for target 'install_defstarget' failed
make[1]: [install_defstarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/definitions/SSM1defs_Engine.xml /home/dev/FreeSSM/definitions/SSM1defs_Engine.xml
Error copying /home/dev/FreeSSM/definitions/SSM1defs_Engine.xml to /home/dev/FreeSSM/definitions/SSM1defs_Engine.xml: Cannot open /home/dev/FreeSSM/definitions/SSM1defs_Engine.xml for input
Makefile.Release:1984: recipe for target 'install_defstarget' failed
make[1]: [install_defstarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/definitions/J2534libs.xml /home/dev/FreeSSM/definitions/J2534libs.xml
Error copying /home/dev/FreeSSM/definitions/J2534libs.xml to /home/dev/FreeSSM/definitions/J2534libs.xml: Cannot open /home/dev/FreeSSM/definitions/J2534libs.xml for input
Makefile.Release:1984: recipe for target 'install_defstarget' failed
make[1]: [install_defstarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/background.png /home/dev/FreeSSM/background.png
Error copying /home/dev/FreeSSM/background.png to /home/dev/FreeSSM/background.png: Cannot open /home/dev/FreeSSM/background.png for input
Makefile.Release:2001: recipe for target 'install_filestarget' failed
make[1]: [install_filestarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/LiberationSans-Bold.ttf /home/dev/FreeSSM/LiberationSans-Bold.ttf
Error copying /home/dev/FreeSSM/LiberationSans-Bold.ttf to /home/dev/FreeSSM/LiberationSans-Bold.ttf: Cannot open /home/dev/FreeSSM/LiberationSans-Bold.ttf for input
Makefile.Release:2001: recipe for target 'install_filestarget' failed
make[1]: [install_filestarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/LiberationSans-BoldItalic.ttf /home/dev/FreeSSM/LiberationSans-BoldItalic.ttf
Error copying /home/dev/FreeSSM/LiberationSans-BoldItalic.ttf to /home/dev/FreeSSM/LiberationSans-BoldItalic.ttf: Cannot open /home/dev/FreeSSM/LiberationSans-BoldItalic.ttf for input
Makefile.Release:2001: recipe for target 'install_filestarget' failed
make[1]: [install_filestarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/LiberationSans-Italic.ttf /home/dev/FreeSSM/LiberationSans-Italic.ttf
Error copying /home/dev/FreeSSM/LiberationSans-Italic.ttf to /home/dev/FreeSSM/LiberationSans-Italic.ttf: Cannot open /home/dev/FreeSSM/LiberationSans-Italic.ttf for input
Makefile.Release:2001: recipe for target 'install_filestarget' failed
make[1]: [install_filestarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/LiberationSans-Regular.ttf /home/dev/FreeSSM/LiberationSans-Regular.ttf
Error copying /home/dev/FreeSSM/LiberationSans-Regular.ttf to /home/dev/FreeSSM/LiberationSans-Regular.ttf: Cannot open /home/dev/FreeSSM/LiberationSans-Regular.ttf for input
Makefile.Release:2001: recipe for target 'install_filestarget' failed
make[1]: [install_filestarget] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /home/dev/FreeSSM/resources/icons/freessm/48x48/FreeSSM.png /home/dev/FreeSSM/FreeSSM.png
make[1]: Leaving directory '/home/dev/FreeSSM'
`

**Comment by Comer352L** [comment]
Looks like you have messed up your access rights.
That usually happens when you mix compilation and/or installation as normal user and as superuser.
There is no need to use sudo.

**Comment by W1JPI** [comment]
Hi Comer352L, I only tried using sudo after failing when running it under the "dev" user. I have previously compiled FreeSSM with no issues. 

I just recreated my VM entirely. I apt installed qt5-default, g++, make, and git. I ran qmake, then make release, and then make release-install, and I got the same issue. 

I did notice that a couple TTF files are deleted when I run make release-install.

**Comment by Comer352L** [comment]
> ... Entering directory '/home/dev/FreeSSM' [...]
Error copying FreeSSM to /home/dev/FreeSSM/FreeSSM ...

Ahh wait, looks like your working directory is /home/dev/FreeSSM.
The destination for the installation is /home/dev/FreeSSM, too.
Of course that doesn't work.

Please note that "make install" on Linux currently just copies all files from the build directory which are required to run FreeSSM into the directory ~/FreeSSM (with ~ beeing the users home directory)
It does not install the Qt library or other dependencies.

While that could (likely) be improved, it has very low priority for me.
The documentation of qmake is horrible and the time is IMHO better spent on creating rpm/deb packages.
Of course I'm willing to accept patches.

If you need to install into a separate directory, you can edit the variable INSTALLDIR in FreeSSM.pro (e.g. unix:INSTALLDIR = /my/path/xyz).
Or simply rename your build directory e.g. to ~/freessm_build.

**Comment by W1JPI** [comment]
Understood, thanks!
