### ISSUE TITLE
does this software support ssm3 

### ISSUE THREAD

**Issue by yipperr** [Comer352L/FreeSSM#35]
hello 

The car i am working on (subaru legacy edm 2011) with the ej204 2.0 cvt is a  a canbus car that runs ssm3 version of the protocol , i got romraider to work on can mode and was able to use the logger portion to log a very limited set of parameters (it doesn't have the ignition retard or knock correction parameters that i am interested in to monitor). When i change the protocol in the romraider logger to "ssm over can" from "Can only"  the software will not connect to the ecu and show some error, i also have to mention i am using a j2534 adapter with the romraider Software (the j2534 adapter is the one manufacturerd by setek called the "dice" popularly used with the vida software of volvo)

I downloaded a compiled binary of the freessm software from the Sourceforge website and it does not detect the j2534 device , even under the preference tab of the software there is no dropdown for j2534 adapters  

so the questions are does this software support logging via j2534 adapters on windows 10 and does it support a 2011 subaru legacy edm with the ej204 engine , i have read that the engine ecu is a hitachi unit 

also can you also explain what this software is based upon ? as in the origin of the source 

thank you for your time

**Comment by Comer352L** [comment]
Don't use sourceforge, it's totally outdated and unmaintained. [*]
Github is the official place where FreeSSM is hosted/developed.

The old version v1.2.5 doesn't support SAE-J2534-interfaces and SSM via CAN.
You will have to compile the latest development code for that (see README.TXT).
If your interface is not detected or the communication with the car doesn't work, compile as debug and send me the debugging output.

[*]:
Initially FreeSSM was hosted at Berlios.de, which has been closed a long time ago.
FreeSSM has been moved to Github, but Sourceforge took over the last version of the Berlios.de page.
It is neither authorized nor maintained by me and so far I wasn't able to delete it. :/

**Comment by yipperr** [comment]
> Don't use sourceforge, it's totally outdated and unmaintained. [*]
> Github is the official place where FreeSSM is hosted/developed.
> 
> The old version v1.2.5 doesn't support SAE-J2534-interfaces and SSM via CAN.
> You will have to compile the latest development code for that (see README.TXT).
> If your interface is not detected or the communication with the car doesn't work, compile as debug and send me the debugging output.
> 
> [*]:
> Initially FreeSSM was hosted at Berlios.de, which has been closed a long time ago.
> FreeSSM has been moved to Github, but Sourceforge took over the last version of the Berlios.de page.
> It is neither authorized nor maintained by me and so far I wasn't able to delete it. :/

thank you for your reply ,if it isn't to much trouble  can you provide the latest binary of the file with debug enabled with j2534 support,  i haven't really build anything in windows and never used QT before , so i wanted to save the pain of trying to figure it all out ,through a lot of build fails and error .

also do you have any source on what ssm really is ? is itsubaru specific obd2 pid ? or some sort of different protocol? , how has ssm changed from ssm3 to ssm 4 software?

thank you for your time much appreciated

**Comment by Comer352L** [comment]
If you are not able to compile the software, you will very likely also not be able to help debugging any problems that might show up.
And what if you need to test patches ?
Do you really expect me to compile the whole software for you each time ?
Sorry, but that's not how it works.

**Comment by yipperr** [comment]
hey 

your right of course, i finally compiled and ran the binary with a cloned dice unit (setek dice clone used by volvo vida diagnostic) and the software complained that the j2534 devices does not support ssm2 or ssm3 , there was a test in the software for testing the device and it failed saying no support for ssm2 and ssm3 and pretty much the whole software wouldn't communicate 

a few question , i was under the impression SSM was just over CAN so why does this need a specific hardware support ? i don't think even think the openport 2.0 is specifically advertised for ssm as its all just over the can protocol ISO15765 , so i am confused of how the software is handling this 

the unit is manufacturered by setek called the dice , the function libary is TSDiCE64.dll , is there a place where the compiled binary save logs ? i had compiled it in debug and i had command prompt displaying errors but din't occur to me to save them in a notepad as i figured there would be a log file for each run 

let me know what else you need 

thank you for your time 


let me know what other information you require regarding this 

thank you for your time

**Comment by yipperr** [comment]
I should also add i used the same dice unit with the romraider logger , it works find in default "obd over can" protocol which is default , but when you change the protocol in the logger to "ssm over can" and try to log more than one parameter the software complains about "ecu init failed Request type not supported. Command: A8 unsupported parameter"

note it only complains when i try to log more than 1 parameter , if only 1 parameter is sampled there are no errors and the values logged seem accurate 

thank you

**Comment by yipperr** [comment]
i think it is better to close this issue and start a new regarding the j2534 devices being reported as not supported
