### ISSUE TITLE
Tactrix 2.0 Windows test fail

### ISSUE THREAD

**Issue by Kartereo** [Comer352L/FreeSSM#37]
I have installed through the 1.2.5 .exe provided on here for windows 10 and installed the tactrix drivers + J2534 DLL. I then went into freessm to test diag interface and I get "interface test failed". What am I doing wrong here.

Edit: forgot to add I am trying this on a 2007 Forester XT

**Comment by Comer352L** [comment]
Version 1.2.5 doesn't support J2534.
It is _very_ old and no longer supported.

**Comment by Kartereo** [comment]
What does the newest version use?

What is the latest version that does support J2534?

Thank you for your time and this project 😁

**Comment by Comer352L** [comment]
> What does the newest version use?
>
> What is the latest version that does support J2534?
>

There is no official release with J2534 support yet.
If you want to test it, you will have to compile the latest source code 
yourself.
