### ISSUE TITLE
Compile for Tactrix Openport 2.0 ?

### ISSUE THREAD

**Issue by AndrewLitchfield** [Comer352L/FreeSSM#41]
Thanks for this project I'd like to use FreeSSM-master with Tactrix Openport 2.0 on Windows 10. I have installed the Tactrix drivers from the vendors website which show up in the Windows Device Manager.  I installed QT open source with the current defaults so it's QT 5.14 with MinGW 7.3.0.

I can build FreeSSM-master OK but after running the exe and selecting J2534 passthrough the debug screen shows "No J2534-libraries found".  Do we have to copy any files around or modify the source code for this to work ?

**Comment by Comer352L** [comment]
Did you build a 64bit application ?
IIRC only a 32bit dll is available for the OpenPort interface.
In that case you are forced to build a 32bit application to be able to 
use this interface (or ask the manufacturer for releasing a 64bit dll, 
too). :/

**Comment by AndrewLitchfield** [comment]
I compiled FreeSSM-master with ming 32-bit and can now connect to ECU & TCU using Tactrix Openport 2.0, thanks @Comer352L

**Comment by Comer352L** [comment]
I have added a few sentences concerning 32/64 bit libraries<->application to README.TXT.
