### ISSUE TITLE
Support for newer (2010+) models

### ISSUE THREAD

**Issue by djolez** [Comer352L/FreeSSM#43]
Hello, I couldn't find a definitive answer on which models are supported, I have a 2012 Forester, will FreeSSM work? Regarding the cable needed I understand that it should be VAG-COM with FT232RL chip, correct me if I am wrong.

Thank you in advance and thanks a lot for working on this.

**Comment by paladinshiva** [comment]
Can you test?

With VAG-COM? And maybe Tactrix.

**Comment by djolez** [comment]
I currently don't have the cable and should buy it, that's why I am asking about compatibility. I already bought a regular OBDII bluetooth scanner (one that uses phone app) which doesn't work, so don't want to buy again if FreeSSM is not compatible

**Comment by Comer352L** [comment]
FreeSSM should work with a 2012 Forester, but a few DTCs/MBs might be 
missing.
You will almost certainly need an interface which supports CAN.
Best choice is a J2534-interface (with ISO-15765-CAN support), e.g. the 
Tactrix OpenPort 2.0.
Serial-Pass-Through (VAG-COM-) interfaces never support CAN.

**Comment by paladinshiva** [comment]
Oh. Well that answers the question. Forgot that those are CAN...

**Comment by djolez** [comment]
Thanks a lot, I will try to find a cable with that spec, closing the issue
