### ISSUE TITLE
error on make translation

### ISSUE THREAD

**Issue by glyptophane** [Comer352L/FreeSSM#47]
$make translation
/usr/lib/qt5/bin/lrelease FreeSSM.pro
make: /usr/lib/qt5/bin/lrelease: Command not found
make: *** [Makefile:291: translation] Error 127

I thought maybe it didn't matter, hoping it was done in english... figured wth, might as well try it.
This was the end of the install-

/usr/lib/qt5/bin/lrelease FreeSSM.pro
make[1]: /usr/lib/qt5/bin/lrelease: Command not found
make[1]: *** [Makefile.Release:2058: install_translation] Error 127
make[1]: Leaving directory '/home/pi/opt/freessm'
make: *** [Makefile:50: release-install] Error 2

did a search for lrelease, only offered for qt4 on this distro
qt4-linguist-tools/stable 4:4.8.7+dfsg-18+deb10u1 i386
  Qt 4 Linguist tools

I tried running it and it brought up the main menu and seems to work ok... Do I need to uninstall freessm/install all of the qt4.8.7 resources/recompile/install (using qt4), or is this something i can ignore and try hooking up to my car? Trying not to get too excited and jump the gun, screw something up accidentally.

Thanks for the fantastic effort!!!!!! So far it's looking amazing!!

**Comment by Comer352L** [comment]
If you are running a Debian based distro, qttools5-dev-tools should be
the package you are looking for.
But yes, program works fine without translations.

**Comment by glyptophane** [comment]
Thanks man!!!

**Comment by flyize** [comment]
I just had this same question. Any chance the README could include this info? Thanks!

**Comment by Comer352L** [comment]
> I just had this same question. Any chance the README could include this info? Thanks!

Sorry for the delay, I've added this information to README.TXT.
