### ISSUE TITLE
Compilation error in FreeSSM.cpp

### ISSUE THREAD

**Issue by ristakaen** [Comer352L/FreeSSM#49]
Debian 10.10, Qt5
Upon compilation, make throws:

src/FreeSSM.cpp:55:26: error: ‘class FreeSSM’ has no member named ‘screen’; did you mean ‘scroll’?
  QScreen *screen = this->screen();
____________________^

**Comment by hegxiten** [comment]
Same happened here at Windows 10, Qt5. Bump

**Comment by Comer352L** [comment]
Fixed now, thanks for the report.
