### ISSUE TITLE
Adjustments empty in TCU

### ISSUE THREAD

**Issue by oflospzoo** [Comer352L/FreeSSM#51]
Hi.

I have a problem with FreeSSM and my Subaru Legacy IV 2.0 (EJ20F) with 4EAT (European version).
My interface connects with no problems to FreeSSM but I don't see any adjustments in TCU i.e. Line Pressure Connection or Correction Of Transfer Duty Ratio. I tried version 1.2.5 and some newer compilations (with ABS/VDC, Cruise Control and AC). I can read TCU and ECU errors, I can monitor some blocks, but no adjustments in TCU. What could be the reason for this? Do I need some other version of FreeSSM or maybe I need some different interface?

**Comment by oflospzoo** [comment]
My interface in based on ft232rl chip.

**Comment by oflospzoo** [comment]
That's screen I'm talking about. In my case there are no adjustment available.

![2021-12-02 18_42_32-Review on SUBARU FreeSSM v1 2 5 diagnostic cable _ OBDII365 com Official Blog — ](https://user-images.githubusercontent.com/46484174/144478894-904050cf-0fcf-4af0-a9a8-12476aa6faf9.png)

**Comment by oflospzoo** [comment]
This is how it looks in my car:

![20211202_200132](https://user-images.githubusercontent.com/46484174/144487358-a2957707-641d-4057-b186-0753cdc635b9.jpg)

**Comment by Comer352L** [comment]
> My interface connects with no problems to FreeSSM but I don't see any adjustments in TCU i.e. Line Pressure Connection or Correction Of Transfer Duty Ratio.

Looks like your TCU/transmission doesn't support these correction values. :-(
FreeSSM displays/offers only adjustments that are supported by the controller.
