### ISSUE TITLE
ABS via J2534?

### ISSUE THREAD

**Issue by jhugo** [Comer352L/FreeSSM#53]
I have a 2014 Crosstrek that is throwing a P0500 code, along with the ABS light.  P0500 suggests one of the ABS speed sensors is bad.  The service manual suggests using SSM to check the speeds reported by the ABS sensors at each wheel against the speedometer.

I have a J2534 adapter which passes the interface test, and can connect to the ECU.  However I fail to connect to the ABS/VDC module.

Digging into the errors reported via a debug build and cross referencing them in the code, I see that communication to the ABS module appears to use the SSM1 protocol, but the J2534 class only appears to support the SSM2 protocol.  Digging around the other issues reported, it looks like the SSM1 protocol is likely invalid for a 2014 Subaru, so even if I were to try to build the serial cable for it, it probably wouldn't work with the car.

Seems like I need ABS communication via SSM2 over J2534.  Am I wrong?  Can that be done?

**Comment by Comer352L** [comment]
Indeed, the ABS dialog currently only supports the old SSM1 protocol.

But the next generation of ABS/VDC controllers does not use SSM2.
Instead, FHI decided to switch to standard ISO-14230, using all the "manufacturer specific" space the norm allows/reserves.
I started working on this a long time ago but, but it's much work and I never found enough resources to come up with something that would be ready to commit.

I'm also pretty sure they switched to CAN later and your 2014 model likely use that.

**Comment by jhugo** [comment]
I see.  Thanks for the explanation
