### ISSUE TITLE
Couldn't set standard port settings with SetPortSettings()

### ISSUE THREAD

**Issue by chainsawbike** [Comer352L/FreeSSM#59]
using the diagnostic interface testing function in preferences  fails with "couldn't open the diagnostic interface" in latest manjaro (9/3/23)

debug build shows the following message:

serialCOM::SetPortSettings:   error: illegal baudrate - the maximum supported baud rate of this device is 0 baud
serialCOM::OpenPort():   Couldn't set standard port settings with SetPortSettings() !

i tried setting the band rate to 38400 with "stty -F /dev/ttyUSB0 38400" which worked ( same user, same terminal )

i am not familiar with the linux tty workings, where should i look next?

**Comment by zaharovrd** [comment]
Maybe something with permissions?

**Comment by chainsawbike** [comment]
to test i have tried joining the same group as ttyUSB0 (uucp), setting permissions to 777 and running as root

still the same error

**Comment by chainsawbike** [comment]
yes it uses the ch341 driver, the device is "kkl vag-com 409.1"

i have used this device in the past with freessm

**Comment by Comer352L** [comment]
Please update to the latest commit.
Can you confirm that it is working now ?

**Comment by chainsawbike** [comment]
yes, latest commit works

yea, i used it about 6 months ago on manjaro ( but a  different laptop ) so i was assuming something underlying changed but could not figure out where to look
