### ISSUE TITLE
Build failure for debug version

### ISSUE THREAD

**Issue by KuusamoMart** [Comer352L/FreeSSM#62]
Using latest sources commit 74c5635, release builds correctly, but debug build fails. Log file from debug build attached.
Build environment is QT5.14.2 in 32 bit Windows 7 OS.

[Debug_build_error.txt](https://github.com/Comer352L/FreeSSM/files/11416106/Debug_build_error.txt)

**Comment by Comer352L** [comment]
Fixed.
