### ISSUE TITLE
EGR relearn and force regen support

### ISSUE THREAD

**Issue by Camzijs** [Comer352L/FreeSSM#63]
Hi, I have a 2010 Legacy 2.0D and P1469 code which requires force regen or a way to tell the ECU that the DPF has been changed to clear. I also have replaced the EGR valve that needs to be calibrated. Is there a way to do all of this and how? 

P.S. Love this freessm project and was a great learning proccess to compile and make it work.

**Comment by Comer352L** [comment]
Also see issue #44.
Sorry, I don't have the resources (time, test vehicles, ...) at the moment and in the near future.
Patches are of course welcome.
