### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by digitaltrousers** [Comer352L/FreeSSM#65]
Hi. I'm having the message "Segmentation fault (core dumped)" on a Fedora laptop when trying to communicate with the ECU.
Adapter is this: https://www.aliexpress.com/item/1005003095063530.html (FTDI FT232 version).
Vehicle is a 2006 (BP) Outback 2.5L.
Here is the terminal output from the debug binary. It's the same whether I do the comms test in preferences or clicking the engine button in the menu.
```
[dan@fedora FreeSSM]$ ./FreeSSM
libpng warning: iCCP: too many profiles
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
SSMP2communication::run():   operation: readCUdata
SSMP2communication_core::SndRcvMessage(...):   sending message:
   80 10 F0 01 BF 40
SSMP2communication_core::SndRcvMessage(...):   received message:
   80 F0 10 39 FF A2 10 02 45 52 16 42 06 F3 FA CB
   84 23 86 02 AC 00 00 00 E0 CE D4 FD B8 60 00 0F
   20 00 00 00 00 00 DC 00 00 5D 1F 30 80 F0 24 00
   00 40 FB 00 E1 00 00 00 00 00 00 C1 F0 A3
Segmentation fault (core dumped)
```
Thanks for any help.

**Comment by Comer352L** [comment]
FIxed now, thanks for the report !

**Comment by maitmandel** [comment]
What was the fix? Is there a PR?
(I'm having the same issue)

**Comment by Comer352L** [comment]
git pull, then rebuild the software.
If it still doesn't work, post the debugging output.
