### ISSUE TITLE
Measuring blocks don't update

### ISSUE THREAD

**Issue by digitaltrousers** [Comer352L/FreeSSM#66]
Hi. Sorry if I'm doing something dumb, but in the 'Engine Control Unit' area, measuring blocks don't update dynamically for me; they only update if I hit 'Stop' and then 'Start' again. I'm using a passthrough serial adapter with FTDI chip.
Thanks.

**Comment by Comer352L** [comment]
You're not thumb, it was another bug. :-(
Fixed now.
